// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PppPricing.API.Data;

#nullable disable

namespace PppPricing.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203170518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("PppPricing.Domain.Models.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppStoreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BundleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StoreConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreConnectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.PppMultiplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegionCode")
                        .IsUnique();

                    b.ToTable("PppMultipliers");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.PriceChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NewPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("PriceChanges");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.StoreConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppleIssuerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppleKeyId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ApplePrivateKeyEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("GoogleAccessTokenEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("GoogleRefreshTokenEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("GoogleTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StoreType")
                        .IsUnique();

                    b.ToTable("StoreConnections");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BasePlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingPeriod")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.SubscriptionPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PppMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PppSuggestedPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "RegionCode")
                        .IsUnique();

                    b.ToTable("SubscriptionPrices");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.App", b =>
                {
                    b.HasOne("PppPricing.Domain.Models.StoreConnection", "StoreConnection")
                        .WithMany("Apps")
                        .HasForeignKey("StoreConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PppPricing.Domain.Models.User", "User")
                        .WithMany("Apps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.PriceChange", b =>
                {
                    b.HasOne("PppPricing.Domain.Models.Subscription", "Subscription")
                        .WithMany("PriceChanges")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PppPricing.Domain.Models.User", "User")
                        .WithMany("PriceChanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.StoreConnection", b =>
                {
                    b.HasOne("PppPricing.Domain.Models.User", "User")
                        .WithMany("StoreConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.Subscription", b =>
                {
                    b.HasOne("PppPricing.Domain.Models.App", "App")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.SubscriptionPrice", b =>
                {
                    b.HasOne("PppPricing.Domain.Models.Subscription", "Subscription")
                        .WithMany("Prices")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.App", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.StoreConnection", b =>
                {
                    b.Navigation("Apps");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.Subscription", b =>
                {
                    b.Navigation("PriceChanges");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("PppPricing.Domain.Models.User", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("PriceChanges");

                    b.Navigation("StoreConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
